### ISSUE TITLE
Suggestion: change frames_create function output

### ISSUE THREAD

**Issue by TK-A369** [knei-knurow/cframes#1]
https://github.com/knei-knurow/cframes/blob/616aaf8e19c54416ba16fb8d07dff7f5fc7b5757/frames.c#L7-L9
Currently user code doesn't know length of generated frame.
I would change function returned type to void and add 2 parameters: pointer to output array and pointer to output length variable.
Something like this:
`void frames_create(uint8_t* header, uint8_t* data, uint8_t data_len, uint8_t *output, uint8_t *output_length)`
And this will be called like this:
`frames_create("MT", "data", 4, frame_buffer, &frame_length)`
Then, user code sends `frame_buffer` (its length is stored in variable `frame_length`).
Also, if `frame_buffer` array is global, there is no problem with allocating it in memory (`malloc` will not be used).

**Comment by TK-A369** [comment]
What do you think about this? If it seems to be good, I can change this.

**Comment by bartekpacia** [comment]
it indeed sounds reasonable, but I have some code changes locally that are quite similar to what you want to do (I just forgot to push them to GitHub). I will push my commits and we'll see:)

**Comment by bartekpacia** [comment]
take a look at my latest commits – it's almost complete (IMHO), and of course, it needs testing.
feel free to submit a new PR – meanwhile I'll close #2 :)

**Comment by TK-A369** [comment]
It has been done a lot of time ago. I forgot to close this issue.
