### ISSUE TITLE
Allow digits in frame prefix

### ISSUE THREAD

**Issue by TK-A369** [knei-knurow/cframes#4]
Currently the frame prefix (first two characters) must be uppercase letters.
I suggest to also allow using digits in prefix.
What do you think, is it good idea? If yes, I can do it.

**Comment by TK-A369** [comment]
If yes, it should also be changed in `frames` library in Go

**Comment by bartekpacia** [comment]
This sounds reasonable, but we need to make sure we won’t break any existing code by doing this change (specifically we need to check dependents or ‘frames’)

**Comment by TK-A369** [comment]
I think `cframes` dependencies shouldn't get broken - if they still use only letters in header, frames will be valid.
`frames` in Go needs to be changed too, otherwise programs which use `frames` will not be able to read frames with digits in header.
But I will check if this won't break existing code.
What programs use `frames` and `cframes` actually, besides `ConcentratorTest`?

**Comment by TK-A369** [comment]
I found that [lidar-tools](https://github.com/knei-knurow/lidar-tools) use `frames` too.

**Comment by bartekpacia** [comment]
[roverd](https://github.com/knei-knurow/roverd) also uses `frames`.

But back to the topic - I think no big problems can be created by this suggested change. 

I can think of only one, a small one: in my opinion, it will look a bit strange when you see `M14+ABCD#C` (C is a CRC, but I omitted it). In this case, `M1` is the header, `4` is the length of the data section, `ABCD` is data. It just looks a bit strange, but it will make sense (for example when we will have 4 motor drivers (`M1`, `M2` and so on).

Can you create a PR for this, both for `frames` and `cframes`? Also, `frames` have tests, so you'll have to make sure they pass and also add another test to make sure that the feature we're discussing is working fine.

**Comment by bartekpacia** [comment]
@TK-A369 we also need to change go implementation as well. Do you have experience with Go or should I do this change?

**Comment by TK-A369** [comment]
No, i haven't programmed in Go yet. If you can change `frames`, please do that.
